hostnames:
  - "verifier-backend-k8s-dev.internal-iden3-dev.com"

image:
  repository: 654654630007.dkr.ecr.eu-west-1.amazonaws.com/verifier_backend
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

env:
  VERIFIER_BACKEND_HOST: "https://verifier-backend-k8s-dev.internal-iden3-dev.com"
  VERIFIER_BACKEND_PORT: "3010"
  VERIFIER_BACKEND_KEY_DIR: "./keys"
  VERIFIER_IPFS_URL: "https://gateway.pinata.cloud"
  VERIFIER_BACKEND_RESOLVER_SETTINGS_PATH: "./resolvers_settings.yaml"
  VERIFIER_BACKEND_CACHE_EXPIRATION: "48h"
  ENVIRONMENT: "dev"
