apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "verifier-backend.fullname" . }}
  labels:
    {{- include "verifier-backend.allLabels" . | nindent 4 }}
data:
  VERIFIER_BACKEND_HOST: {{ .Values.env.VERIFIER_BACKEND_HOST | quote }}
  VERIFIER_BACKEND_PORT: {{ .Values.env.VERIFIER_BACKEND_PORT | quote }}
  VERIFIER_BACKEND_KEY_DIR: {{ .Values.env.VERIFIER_BACKEND_KEY_DIR | quote }}
  VERIFIER_IPFS_URL: {{ .Values.env.VERIFIER_IPFS_URL | quote }}
  VERIFIER_BACKEND_RESOLVER_SETTINGS_PATH: {{ .Values.env.VERIFIER_BACKEND_RESOLVER_SETTINGS_PATH | quote }}
  VERIFIER_BACKEND_CACHE_EXPIRATION: {{ .Values.env.VERIFIER_BACKEND_CACHE_EXPIRATION | quote }}
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
